# Generated by Django 4.2.3 on 2023-07-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=300, verbose_name='Diagnosis')),
                ('diagnosis_type', models.CharField(choices=[('Preliminary', 'Preliminary'), ('Clinical', 'Clinical'), ('Final', 'Final')], default='Preliminary', max_length=30, verbose_name='Diagnosis Type')),
                ('other_diseases', models.TextField(blank=True, null=True, verbose_name='Other Disease')),
                ('summary', models.TextField(blank=True, max_length=120, null=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('complications', models.TextField(blank=True, null=True, verbose_name='Complication')),
                ('diagnosis_date', models.DateField(verbose_name='Diagnosis Date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnosis',
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='MedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Identifier')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'verbose_name': 'Med_area',
                'verbose_name_plural': 'Med_areas',
                'db_table': 'med_area',
            },
        ),
        migrations.CreateModel(
            name='MedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('med_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medarea')),
            ],
            options={
                'verbose_name': 'Med_test',
                'verbose_name_plural': 'Med_tests',
                'db_table': 'med_test',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('finish_date', models.DateField(verbose_name='Finish Date')),
                ('summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diagnosis', verbose_name='Diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'db_table': 'treatment',
            },
        ),
        migrations.CreateModel(
            name='TestRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Test')),
                ('short_name', models.CharField(max_length=200, verbose_name='Short Name)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Discription')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Summary')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('test_date', models.DateField(verbose_name='Test Date')),
                ('test_name', models.CharField(max_length=200, null=True, verbose_name='Test Name')),
                ('normal_value', models.CharField(max_length=200, null=True, verbose_name='Normal Value')),
                ('results', models.CharField(max_length=200, null=True, verbose_name='Results')),
                ('units', models.CharField(max_length=50, null=True, verbose_name='Units')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_recs', to='main.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Test_rec',
                'verbose_name_plural': 'Test_recs',
                'db_table': 'test_rec',
            },
        ),
        migrations.CreateModel(
            name='PatientMedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medtest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'verbose_name': 'Patient_med_test',
                'verbose_name_plural': 'Patient_med_tests',
                'db_table': 'patient_med_test',
            },
        ),
    ]
