# Generated by Django 4.2.3 on 2023-07-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='roomCharge',
        ),
    ]
