# Generated by Django 4.2.3 on 2023-07-19 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('description', models.TextField(default='')),
                ('address', models.CharField(default='', max_length=100)),
                ('shift_start_time', models.TimeField(max_length=10)),
                ('shift_end_time', models.TimeField(max_length=10)),
                ('qualification_name', models.CharField(max_length=100)),
                ('nmc_number', models.CharField(default='', max_length=10)),
                ('education_training', models.TextField(default='')),
                ('hospital_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Physician', 'Physician'), ('Dentistry', 'Dentistry'), ('Cardiology', 'Cardiology'), ('ENT Specialists', 'ENT Specialists'), ('Dietitian', 'Dietitian'), ('Endocrinology', 'Endocrinology'), ('Blood Screening', 'Blood Screening'), ('Eye Care', 'Eye Care'), ('Physical Therapy', 'Physical Therapy'), ('Neurology', 'Neurology'), ('Gynaecology', 'Gynaecology'), ('Pediatrics', 'Pediatrics'), ('Ophthalmology', 'Ophthalmology'), ('Orthopedic', 'Orthopedic'), ('Pulmonologist', 'Pulmonologist'), ('Radiologist', 'Radiologist'), ('General Surgeon', 'General Surgeon')], default='Physician', max_length=50)),
                ('professional_experience', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
